version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: ApiGatewayDb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  # API Gateway service
  apigateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apigateway
    depends_on:
      - mongodb
    ports:
      - "8080:80"  # Cấu hình cho API
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=ApiGatewayDb

volumes:
  esdata:
